Repository alephium/gpu-miner, pull requests merged in 2021-12, with the labels that each got.

#36 Add windows run-miner script
  README.md
  run-miner.ps1
Labels: ALPH-200

#37 Update run-miner.ps1 to use API key
  run-miner.ps1
Labels: ALPH-25

#41 memory leaks fix and other improvements
  src/main.cu
  src/mining.h
  src/template.h
Labels: ALPH-1000

#43 more memory leaks fix
  src/main.cu
  src/messages.h
Labels: ALPH-500
